// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aula18_AS.Data.Context;

#nullable disable

namespace aula18_AS.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230630001113_ModificatioForeignKeyCpf")]
    partial class ModificatioForeignKeyCpf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("aula18_AS.Domain.Entities.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DbSetAutor");
                });

            modelBuilder.Entity("aula18_AS.Domain.Entities.AutoresLivro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutorCpf")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AutoresId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LivroCodBarras")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LivrosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AutoresId");

                    b.HasIndex("LivrosId");

                    b.ToTable("DbSetAutorLivro");
                });

            modelBuilder.Entity("aula18_AS.Domain.Entities.Emprestimo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LivroCodBarras")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LivroId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioCpf")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("DbSetEmprestimo");
                });

            modelBuilder.Entity("aula18_AS.Domain.Entities.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodBarras")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroPag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DbSetLivro");
                });

            modelBuilder.Entity("aula18_AS.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DbSetUsuario");
                });

            modelBuilder.Entity("aula18_AS.Domain.Entities.AutoresLivro", b =>
                {
                    b.HasOne("aula18_AS.Domain.Entities.Autor", "Autores")
                        .WithMany("LivrosAutores")
                        .HasForeignKey("AutoresId");

                    b.HasOne("aula18_AS.Domain.Entities.Livro", "Livros")
                        .WithMany("LivrosAutores")
                        .HasForeignKey("LivrosId");

                    b.Navigation("Autores");

                    b.Navigation("Livros");
                });

            modelBuilder.Entity("aula18_AS.Domain.Entities.Emprestimo", b =>
                {
                    b.HasOne("aula18_AS.Domain.Entities.Livro", "Livro")
                        .WithMany("Emprestimos")
                        .HasForeignKey("LivroId");

                    b.HasOne("aula18_AS.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Emprestimo")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Livro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("aula18_AS.Domain.Entities.Autor", b =>
                {
                    b.Navigation("LivrosAutores");
                });

            modelBuilder.Entity("aula18_AS.Domain.Entities.Livro", b =>
                {
                    b.Navigation("Emprestimos");

                    b.Navigation("LivrosAutores");
                });

            modelBuilder.Entity("aula18_AS.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Emprestimo");
                });
#pragma warning restore 612, 618
        }
    }
}
